# Generated by Django 2.2.7 on 2019-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='host',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
