# Generated by Django 2.2.7 on 2019-11-20 21:18

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20191120_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
